apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network
  namespace: openshift-cnv
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bridge-network",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "br1",
        "ipam": {}
      },
      {
        "type": "cnv-tuning"
      }
    ]
  }'
