apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-ens2-policy 
spec:
  nodeSelector: 
    node-role.kubernetes.io/master: "" 
  desiredState:
    interfaces:
      - name: br1
        description: Linux bridge with en2 as a port 
        type: linux-bridge
        state: up
        ipv4:
          dhcp: true
          enabled: true
        bridge:
          options:
            stp:
              enabled: true
          port:
            - name: ens2